# This is an example config file for LMOS
# It can either be modified for your application
# or used as a schema guide when writing your own

# yaml-language-server: $schema=https://lmos-io.github.io/LMOS-config/schema.json

internal_configuration: # Defines configs for internal assets that support services
  redis: # configuration of redis asset
    redis_url: redis://localhost:6379

  database:
    database_url: postgresql://postgres:postgres@localhost:5432/postgres

  prometheus:
    logging_enabled: True
    log_level: info
    endpoint: http://YourPrometheusServer:80

services:
  router:
    log_request_dump_max_queue_size: 100 # Start worker if queue reaches 100 entries
    log_request_dump_queue_timeout: 10 # Start worker if worker hasn't ran for 10 seconds

  llm_runner: # Defining all llm_runner services on the network
    - name: llama-3.1-70b # config for a single llm_runner container
      type: vllm # what inference service is deploying the model
      location: /your/path/to/model_folder # local file path or hf repo
      alias: # model name(s) that map to this model when the client makes a request
        - llama-3.1-70b
        - llama-3.1-70b-2

    - name: hermes-3.1-70b # config for a second llm_runner container
      type: exl2
      location: /your/path/to/model_folder
      alias:
        - hermes-3.1-70b
        - hermes-3.1-70b-2
        - gpt-4o

  stt_runner: # Defining all stt_runner services on the network
    - name: whisper-large-en
      location: /your/path/to/model_folder # local file path or hf repo
      alias: # model name(s) that map to this model when the client makes a request
        - whisper

  tts_runner: # Defining all tts_runner services on the network
    - name: XTTS-v2
      type: coqui_runner # Type of backend to run the tts model (prob link to breakout docs)
      location: /your/path/to/model_folder # local file path or hf repo
      alias:
        - XTTS-v2

  rerank_runner: # Defining all reranking services on the network
    - name: reranker
      type: some-reraker-structure # Type of backend for the reranker model you choose
      location: /your/path/to/model_folder # local file path or hf repo
      alias:
        - reranker