name: Generate and Publish Schema

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run Python script to generate schema.json
        run: |
          python export-schema.py

      - name: Commit and push schema.json to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout gh-pages || git checkout -b gh-pages
          mkdir -p docs
          mv schema.json docs/schema.json
          git add -f docs/schema.json
          git commit -m "Update schema.json" || echo "No changes to commit"
          git push -f "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
